// seed.js
import mongoose from "mongoose";
import dotenv from "dotenv";
import { Product } from "./model/product.model.js";

dotenv.config();

// 30 dummy products
const products = [
  // Men
  {
    name: "Classic White T-Shirt",
    description: "Soft cotton unisex t-shirt for everyday wear.",
    image: "https://dummyimage.com/400x400/ffffff/000000&text=White+T-Shirt",
    category: "men",
    color: "white",
    size: "m",
    price: 299,
    stock: 50,
    isActive: true,
  },
  {
    name: "Black Leather Jacket",
    description: "Stylish black leather jacket for men.",
    image: "https://dummyimage.com/400x400/000000/ffffff&text=Leather+Jacket",
    category: "men",
    color: "black",
    size: "l",
    price: 4999,
    stock: 20,
    isActive: true,
  },
  {
    name: "Blue Denim Jeans",
    description: "Comfortable blue denim jeans.",
    image: "https://dummyimage.com/400x400/0000ff/ffffff&text=Denim+Jeans",
    category: "men",
    color: "blue",
    size: "l",
    price: 1499,
    stock: 35,
    isActive: true,
  },
  {
    name: "Grey Hoodie",
    description: "Warm and cozy grey hoodie.",
    image: "https://dummyimage.com/400x400/808080/ffffff&text=Grey+Hoodie",
    category: "men",
    color: "grey",
    size: "xl",
    price: 799,
    stock: 40,
    isActive: true,
  },
  {
    name: "Red Sports Shoes",
    description: "Lightweight red running shoes.",
    image: "https://dummyimage.com/400x400/ff0000/ffffff&text=Sports+Shoes",
    category: "men",
    color: "red",
    size: "42",
    price: 1999,
    stock: 25,
    isActive: true,
  },
  {
    name: "Navy Blue Shirt",
    description: "Formal navy blue shirt for office wear.",
    image: "https://dummyimage.com/400x400/000080/ffffff&text=Blue+Shirt",
    category: "men",
    color: "blue",
    size: "m",
    price: 899,
    stock: 30,
    isActive: true,
  },
  {
    name: "Brown Belt",
    description: "Genuine leather brown belt.",
    image: "https://dummyimage.com/400x400/a52a2a/ffffff&text=Brown+Belt",
    category: "men",
    color: "brown",
    size: "l",
    price: 499,
    stock: 60,
    isActive: true,
  },
  {
    name: "Black Cap",
    description: "Adjustable black baseball cap.",
    image: "https://dummyimage.com/400x400/000000/ffffff&text=Black+Cap",
    category: "men",
    color: "black",
    size: "free",
    price: 199,
    stock: 70,
    isActive: true,
  },
  {
    name: "White Sneakers",
    description: "Classic white sneakers for casual wear.",
    image: "https://dummyimage.com/400x400/ffffff/000000&text=White+Sneakers",
    category: "men",
    color: "white",
    size: "41",
    price: 2499,
    stock: 30,
    isActive: true,
  },
  {
    name: "Black Formal Pants",
    description: "Slim fit black formal pants.",
    image: "https://dummyimage.com/400x400/000000/ffffff&text=Formal+Pants",
    category: "men",
    color: "black",
    size: "l",
    price: 1299,
    stock: 25,
    isActive: true,
  },

  // Women
  {
    name: "Floral Summer Dress",
    description: "Lightweight floral summer dress.",
    image: "https://dummyimage.com/400x400/ff69b4/ffffff&text=Summer+Dress",
    category: "women",
    color: "pink",
    size: "m",
    price: 1199,
    stock: 40,
    isActive: true,
  },
  {
    name: "Black Handbag",
    description: "Elegant black leather handbag.",
    image: "https://dummyimage.com/400x400/000000/ffffff&text=Handbag",
    category: "women",
    color: "black",
    size: "medium",
    price: 2499,
    stock: 35,
    isActive: true,
  },
  {
    name: "White Sandals",
    description: "Comfortable white sandals.",
    image: "https://dummyimage.com/400x400/ffffff/000000&text=White+Sandals",
    category: "women",
    color: "white",
    size: "38",
    price: 799,
    stock: 50,
    isActive: true,
  },
  {
    name: "Red Evening Gown",
    description: "Elegant red evening gown for parties.",
    image: "https://dummyimage.com/400x400/ff0000/ffffff&text=Evening+Gown",
    category: "women",
    color: "red",
    size: "l",
    price: 3999,
    stock: 15,
    isActive: true,
  },
  {
    name: "Blue Denim Jacket",
    description: "Casual blue denim jacket for women.",
    image: "https://dummyimage.com/400x400/0000ff/ffffff&text=Denim+Jacket",
    category: "women",
    color: "blue",
    size: "m",
    price: 1499,
    stock: 30,
    isActive: true,
  },
  {
    name: "Black Heels",
    description: "Stylish black high heels.",
    image: "https://dummyimage.com/400x400/000000/ffffff&text=Black+Heels",
    category: "women",
    color: "black",
    size: "39",
    price: 1999,
    stock: 20,
    isActive: true,
  },
  {
    name: "Yellow Top",
    description: "Bright yellow casual top.",
    image: "https://dummyimage.com/400x400/ffff00/000000&text=Yellow+Top",
    category: "women",
    color: "yellow",
    size: "s",
    price: 699,
    stock: 45,
    isActive: true,
  },
  {
    name: "Green Skirt",
    description: "Flowy green skirt.",
    image: "https://dummyimage.com/400x400/008000/ffffff&text=Green+Skirt",
    category: "women",
    color: "green",
    size: "m",
    price: 899,
    stock: 30,
    isActive: true,
  },
  {
    name: "Beige Cardigan",
    description: "Soft beige cardigan for winter.",
    image: "https://dummyimage.com/400x400/f5f5dc/000000&text=Cardigan",
    category: "women",
    color: "beige",
    size: "l",
    price: 1299,
    stock: 25,
    isActive: true,
  },
  {
    name: "Purple Scarf",
    description: "Elegant purple scarf.",
    image: "https://dummyimage.com/400x400/800080/ffffff&text=Scarf",
    category: "women",
    color: "purple",
    size: "free",
    price: 399,
    stock: 50,
    isActive: true,
  },

  // Kids
  {
    name: "Kids Red T-Shirt",
    description: "Soft cotton red t-shirt for kids.",
    image: "https://dummyimage.com/400x400/ff0000/ffffff&text=Kids+T-Shirt",
    category: "kids",
    color: "red",
    size: "s",
    price: 299,
    stock: 60,
    isActive: true,
  },
  {
    name: "Kids Blue Jeans",
    description: "Comfortable blue denim jeans for kids.",
    image: "https://dummyimage.com/400x400/0000ff/ffffff&text=Kids+Jeans",
    category: "kids",
    color: "blue",
    size: "m",
    price: 499,
    stock: 50,
    isActive: true,
  },
  {
    name: "Kids Green Hoodie",
    description: "Warm green hoodie for kids.",
    image: "https://dummyimage.com/400x400/008000/ffffff&text=Kids+Hoodie",
    category: "kids",
    color: "green",
    size: "l",
    price: 699,
    stock: 40,
    isActive: true,
  },
  {
    name: "Kids Yellow Sandals",
    description: "Comfortable yellow sandals for kids.",
    image: "https://dummyimage.com/400x400/ffff00/000000&text=Kids+Sandals",
    category: "kids",
    color: "yellow",
    size: "32",
    price: 399,
    stock: 50,
    isActive: true,
  },
  {
    name: "Kids Pink Dress",
    description: "Cute pink dress for girls.",
    image: "https://dummyimage.com/400x400/ff69b4/ffffff&text=Kids+Dress",
    category: "kids",
    color: "pink",
    size: "s",
    price: 799,
    stock: 30,
    isActive: true,
  },
  {
    name: "Kids Black Sneakers",
    description: "Lightweight black sneakers for kids.",
    image: "https://dummyimage.com/400x400/000000/ffffff&text=Kids+Sneakers",
    category: "kids",
    color: "black",
    size: "34",
    price: 999,
    stock: 40,
    isActive: true,
  },
  {
    name: "Kids Orange T-Shirt",
    description: "Vibrant orange t-shirt for kids.",
    image: "https://dummyimage.com/400x400/ffa500/ffffff&text=Kids+T-Shirt",
    category: "kids",
    color: "orange",
    size: "m",
    price: 299,
    stock: 50,
    isActive: true,
  },
  {
    name: "Kids Grey Shorts",
    description: "Cool grey shorts for boys.",
    image: "https://dummyimage.com/400x400/808080/ffffff&text=Kids+Shorts",
    category: "kids",
    color: "grey",
    size: "l",
    price: 399,
    stock: 35,
    isActive: true,
  },
  {
    name: "Kids Blue Cap",
    description: "Adjustable blue cap for kids.",
    image: "https://dummyimage.com/400x400/0000ff/ffffff&text=Kids+Cap",
    category: "kids",
    color: "blue",
    size: "free",
    price: 199,
    stock: 45,
    isActive: true,
  },
  {
    name: "Kids White Sneakers",
    description: "Classic white sneakers for kids.",
    image: "https://dummyimage.com/400x400/ffffff/000000&text=Kids+Sneakers",
    category: "kids",
    color: "white",
    size: "33",
    price: 899,
    stock: 30,
    isActive: true,
  },
];

// Connect and insert
const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB connected");

    // Clear existing products
    await Product.deleteMany();
    console.log("Existing products deleted");

    // Insert new products
    await Product.insertMany(products);
    console.log("Products inserted successfully");

    process.exit();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
};

seedDB();
